jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@v3
    - uses: DeterminateSystems/magic-nix-cache-action@v13
    - run: nix profile add nixpkgs#devenv
    - run: devenv test
'on':
  push: {}
